INSERT INTO CURRENCY VALUES (DEFAULT, 'USD', '美元', '&#36;', 27578.4003, 'United States Dollar', CURRENT_TIMESTAMP);
INSERT INTO CURRENCY VALUES (DEFAULT, 'GBP', '英鎊', '&pound;', 23142.4545, 'British Pound Sterling', CURRENT_TIMESTAMP);
INSERT INTO CURRENCY VALUES (DEFAULT, 'EUR', '歐元', '&euro;', 23142.4545, 'Euro', CURRENT_TIMESTAMP);

