create table CURRENCY
(
    serial_num  INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    code        VARCHAR(10) NOT NULL,
    name        VARCHAR(10),
    symbol      VARCHAR(32),
    rate        DECIMAL(10,4),
    description VARCHAR(100),
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX codeIdx ON CURRENCY (code);